In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import os

In [2]:
#load the original data file
file = os.path.join('..','SHR76_17.csv')
MasterHomicide_df = pd.read_csv(file)
MasterHomicide_df.head()

,ID,CNTYFIPS,Ori,State,Agency,Agentype,Source,Solved,Year,StateName,...,OffEthnic,Weapon,Relationship,Circumstance,Subcircum,VicCount,OffCount,FileDate,fstate,MSA
0,197601001AKASP00,"Juneau, AK",AKASP00,Alaska,State Troopers,Primary state LE,FBI,Yes,1976,ALASKA,...,Unknown or not reported,Knife or cutting instrument,Husband,Other arguments,NaN,0,0,30180.0,Alaska,Rural Alaska
1,197601001AL00102,"Jefferson, AL",AL00102,Alabama,Birmingham,Municipal police,FBI,Yes,1976,ALA,...,Unknown or not reported,Shotgun,Acquaintance,Felon killed by private citizen,Felon killed in commission of a crime,0,0,30180.0,Alabama,"Birmingham-Hoover, AL"
2,197601001AL00104,"Jefferson, AL",AL00104,Alabama,Fairfield,Municipal police,FBI,Yes,1976,ALA,...,Unknown or not reported,Shotgun,Wife,Other,NaN,0,0,30180.0,Alabama,"Birmingham-Hoover, AL"
3,197601001AL00106,"Jefferson, AL",AL00106,Alabama,Leeds,Municipal police,FBI,Yes,1976,ALA,...,Unknown or not reported,Knife or cutting instrument,Brother,Other arguments,NaN,0,0,30180.0,Alabama,"Birmingham-Hoover, AL"
4,197601001AL00201,"Mobile, AL",AL00201,Alabama,Mobile,Municipal police,FBI,Yes,1976,ALA,...,Unknown or not reported,Strangulation - hanging,Acquaintance,Circumstances undetermined,NaN,0,0,30180.0,Alabama,"Mobile, AL"

In [3]:
MasterHomicide_df = MasterHomicide_df.reset_index()

In [4]:
homicide_df1 = MasterHomicide_df.loc[MasterHomicide_df['index']<=200000,:]
homicide_df1
len(homicide_df1)
homicide_df1.head()
homicide_df1.to_csv("ProjectData/MurderData1.csv", index=False)

In [6]:
homicide_df2 = MasterHomicide_df.loc[(MasterHomicide_df['index']>= 200001) & (MasterHomicide_df['index']<= 400000),:]
homicide_df2
len(homicide_df2)
homicide_df2.head()
homicide_df2.to_csv("ProjectData/MurderData2.csv", index=False)

In [7]:
#homicide_df3 = homicide_df.loc[(homicide_df['index'] = 0 ),:]
homicide_df3 = MasterHomicide_df.loc[(MasterHomicide_df['index']>= 400001) & (MasterHomicide_df['index']<= 600000),:]
homicide_df3
homicide_df3.head()
homicide_df3.to_csv("ProjectData/MurderData3.csv", index=False)

In [8]:
homicide_df4 = MasterHomicide_df.loc[(MasterHomicide_df['index']>= 600001) & (MasterHomicide_df['index']<= 800000),:]
homicide_df4
len(homicide_df4)
homicide_df4.head()
homicide_df4.to_csv("ProjectData/MurderData4.csv", index=False)

In [10]:
m1 = pd.read_csv("ProjectData/MurderData1.csv")
m1_df = pd.DataFrame(m1)

m2 = pd.read_csv("ProjectData/MurderData2.csv")
m2_df = pd.DataFrame(m2)

m3 = pd.read_csv("ProjectData/MurderData3.csv")
m3_df = pd.DataFrame(m3)

m4 = pd.read_csv("ProjectData/MurderData4.csv")
m4_df = pd.DataFrame(m4)

a = m1_df
b = m2_df
c = m3_df
d = m4_df
#a.index = x.index  # make duplicate indices!
murderData1_df = pd.concat([a, b])
murderData2_df = pd.concat([murderData1_df, c])
homicide_df = pd.concat([murderData2_df, d])

homicide_df.head()
len(homicide_df)

769753

In [11]:
#create a list of midwest states
midwest_states = ['Minnesota',
                  'Kansas',
                  'Nebraska',
                  'Iowa',
                  'South Dakota',
                  'North Dakota',
                  'Wisconsin',
                  'Michigan',
                  'Indiana',
                  'Ohio',
                  'Missouri',
                  'Illinois']

#create the dataframe for the midwest states from the original data
midwest_homicide_df = homicide_df[homicide_df['State'].isin(midwest_states)]
midwest_homicide_df = midwest_homicide_df.drop(columns = 'index', axis = 1)
midwest_homicide_df = midwest_homicide_df.reset_index(drop = True)
midwest_homicide_df.head()

,ID,CNTYFIPS,Ori,State,Agency,Agentype,Source,Solved,Year,StateName,...,OffEthnic,Weapon,Relationship,Circumstance,Subcircum,VicCount,OffCount,FileDate,fstate,MSA
0,197601001IA00801,"Boone, IA",IA00801,Iowa,Boone,Municipal police,FBI,No,1976,IOWA,...,Unknown or not reported,Knife or cutting instrument,Relationship not determined,Other arguments,NaN,0,0,30180.0,Iowa,Rural Iowa
1,197601001IA04400,"Henry, IA",IA04400,Iowa,Henry County,Sheriff,FBI,Yes,1976,IOWA,...,Unknown or not reported,"Handgun - pistol, revolver, etc",Acquaintance,Robbery,NaN,0,0,30180.0,Iowa,Rural Iowa
2,197601001IA05202,"Johnson, IA",IA05202,Iowa,Iowa City,Municipal police,FBI,Yes,1976,IOWA,...,Unknown or not reported,"Handgun - pistol, revolver, etc",Acquaintance,Other arguments,NaN,0,0,30180.0,Iowa,"Iowa City, IA"
3,197601001IA05701,"Linn, IA",IA05701,Iowa,Cedar Rapids,Municipal police,FBI,Yes,1976,IOWA,...,Unknown or not reported,"Handgun - pistol, revolver, etc",Husband,Other arguments,NaN,0,0,30180.0,Iowa,"Cedar Rapids, IA"
4,197601001IA05703,"Linn, IA",IA05703,Iowa,Hiawatha,Municipal police,FBI,Yes,1976,IOWA,...,Unknown or not reported,"Handgun - pistol, revolver, etc",Stranger,Brawl due to influence of alcohol,NaN,0,0,30180.0,Iowa,"Cedar Rapids, IA"

In [12]:
#create midwest murder data csv
midwest_homicide_df.to_csv("MidwestMurderData.csv", index=False)

The events in the technology timeline events were sourced from three websites:

â€¢ https://www.explainthatstuff.com/timeline.html

â€¢ https://policetechnology.wordpress.com/timeline-of-technology/

â€¢ http://www.softschools.com/timelines/forensic_science_timeline/99/

In [13]:
#load the technology timeline
tfile = os.path.join('ProjectData','TechnologyTimeline.csv')
tcsv = pd.read_csv(tfile, encoding = 'unicode_escape')

#create technology dataframe
tech_df = pd.DataFrame(tcsv)

#sort data by year
tech_df = tech_df.sort_values(['Year'])

#match the start year to the murder dataset
tech_df = tech_df.loc[tech_df['Year'] >= 1976,:]

#select events in which we predict an impact on solved murder
slvd_impact = tech_df.loc[tech_df['Predicted Impact'] == 'yes',:]
slvd_impact

,Year,Discovery,Description,Predicted Impact
38,1979,Auto fingerprint system first used,Royal Canadian Mounted Police implement first ...,yes
40,1983,Advances in DNA lead to conviction (1983-86),DNA fingerprinting led to conviction of Colin ...,yes
39,1984,DNA technique for unique ID,DNA fingerprinting techniques developed by Sir...,yes
41,1987,DNA catches the criminal,Tommy Lee Andrews convicted of a series of sex...,yes
9,1989,Internet,Tim Berners-Lee invents the World Wide Web.,yes
13,1994,VoIP,Israeli computer scientists Alon Cohen and Lio...,yes
42,1996,DNA evidence certified,National Academy of Sciences announces DNA evi...,yes
17,1997,Wireless Internet,Electronics companies agree to make Wi-Fi a wo...,yes
43,1998,The National DNA Index System (NDIS) becomes o...,NaN,yes
44,1999,Faster fingerprint IDs,FBI establishes the integrated automated finge...,yes
45,2001,Faster DNA IDs,Technology speeds up DNA profiling time from 6...,yes
28,2007,Cellphones,Apple introduces a touchscreen cellphone calle...,yes
46,2007,Footwear detection system,Britain's Forensic Science Service develops on...,yes
47,2008,Detection after cleaning,A way for scientists to visualize fingerprints...,yes
29,2010,Computers,Apple releases its touchscreen tablet computer...,yes
49,2011,4 second dental match,Japanese researchers develop a dental x-ray ma...,yes
48,2011,Facial sketches matched to photos,Michigan state university develops software th...,yes
50,2012,Warrentles phone tracking,Police officers were given the permission to t...,yes

In [14]:
#create President Dataframe
pfile = os.path.join('ProjectData','Presidents.csv')
pcsv = pd.read_csv(pfile, encoding = 'unicode_escape')
pres_df = pd.DataFrame(pcsv)
pres_df.head()

   Year       President       Party
0  1974  Gerald R. Ford  Republican
1  1975  Gerald R. Ford  Republican
2  1976  Gerald R. Ford  Republican
3  1977    Jimmy Carter    Democrat
4  1978    Jimmy Carter    Democrat